CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'uyilmaz'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON wordpress.* TO 'uyilmaz'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root1234';